import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#e8e2d4",
        "surface-tint": "#ffb3b5",
        "error-container": "#93000a",
        "on-tertiary-container": "#7cbaa5",
        "on-tertiary-fixed": "#002018",
        "on-secondary-fixed": "#1d1c13",
        "tertiary-container": "#004b3b",
        "surface-variant": "#353535",
        "primary-container": "#7a1f2b",
        background: "#131313",
        "inverse-primary": "#a13c46",
        "surface-charcoal": "#1A1A1A",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#dcc0c0",
        secondary: "#cbc6b9",
        "outline-variant": "#564242",
        "on-tertiary-fixed-variant": "#0a5040",
        "text-muted": "#A3A3A3",
        "surface-dim": "#131313",
        "surface-container": "#20201f",
        "inverse-surface": "#e5e2e1",
        "on-error": "#690005",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353535",
        "on-primary-fixed": "#40000c",
        "on-secondary-container": "#bab5a8",
        "on-secondary-fixed-variant": "#49473d",
        "on-primary": "#630c1c",
        "pure-white": "#FFFFFF",
        "on-background": "#e5e2e1",
        surface: "#131313",
        "surface-container-high": "#2a2a2a",
        "surface-bright": "#393939",
        "secondary-container": "#49473d",
        "tertiary-fixed-dim": "#94d3be",
        tertiary: "#94d3be",
        "tertiary-fixed": "#b0f0d9",
        "on-secondary": "#333027",
        primary: "#ffb3b5",
        "on-tertiary": "#00382b",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed-variant": "#822530",
        "primary-fixed-dim": "#ffb3b5",
        outline: "#a48b8b",
        "primary-fixed": "#ffdada",
        "text-cream": "#F7F1E3",
        "secondary-fixed-dim": "#cbc6b9",
        "on-primary-container": "#ff8b92",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "inverse-on-surface": "#313030",
        "deep-maroon": "#7A1F2B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-gap-desktop": "120px",
        "section-gap-mobile": "64px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        "nav-link": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "label-caps": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "nav-link": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
